name: sysadmin
description: "Building GUI for the Linux System Administrator"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.30+10030

environment:
    sdk: ^3.5.3

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    concentric_transition: ^1.0.3
    flutter_svg:
    flutter_secure_storage: ^9.2.2
    dartssh2: ^2.10.0
    file_picker: ^8.1.3
    xterm: ^4.0.0
    flutter_expandable_fab: ^2.3.0
    path: ^1.9.0
    permission_handler: ^11.3.1
    flutter_scrolling_fab_animated: ^0.1.5
    marquee: ^2.3.0
    intl: ^0.19.0
    cron_parser: ^0.5.0
    flutter_riverpod: ^2.6.1
    local_auth: ^2.3.0
    shared_preferences: ^2.5.1
    syncfusion_flutter_charts: ^29.1.33
    flutter_launcher_icons: ^0.14.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/onboarding/svgs/
        - assets/about/
        - assets/

    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700

# App Logo Configuration
flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/Logo.png"
    minimum-android-sdk: 21
    remove_alpha_ios: true
    adaptive_icon_background: "#AADDBF00"
    adaptive_icon_foreground: "assets/LogoRound.png"
