blank_issues_enabled: false
contact_links:
  - name: 📚 sysAdmin Documentation
    url: https://github.com/prathameshkhade/sysAdmin/wiki
    about: Check our documentation before creating an issue
  - name: 💬 GitHub Discussions
    url: https://github.com/prathameshkhade/sysAdmin/discussions
    about: Please ask and answer questions here
  - name: 📧 Email Support
    url: mailto:pkhade2865+sysadmin@gmail.com
    about: Contact us directly for sensitive or security issues
